### ISSUE TITLE
Delete Vehicle

### ISSUE THREAD

**Issue by SM-Marc** [SM-BJS/stowmarines-mission-framework#4]
Delete Vehicle interaction in Alpha/Phoenix Garage isn't working.
Only works when in driver seat and doesn't delete the vehicle you are in or any vehicle around it or inside the garage.

EDIT: the Delete button shows up at the gate thats where it doesnt work inside next to the orange barriers it works

**Comment by SM-BJS** [comment]
I'll give this a test today. This is an issue with the training map and not the framework so could you post this on this repo when you are able to: https://github.com/SM-BJS/StowMarines-Training-Map/issues

Thanks.
